### LISTAR ADMINISTRADOR
GET http://127.0.0.1:3000/api/administrador

### ELIMINAR ADMINISTRADOR 
DELETE http://127.0.0.1:3000/api/administrador/7

### OBTENER ADMINISTRADOR
GET http://127.0.0.1:3000/api/administrador/7


### OBTENER USUARIO
GET http://127.0.0.1:3000/api/usuario/

### ELIMINAR USUARIO
DELETE http://127.0.0.1:3000/api/usuario/13


### AGREGAR ADMINISTRADOR
POST http://127.0.0.1:3000/api/administrador
Content-Type: application/json
Accept: application/json

{
	"ci": "9091",
	"nombre": "9091",
	"fecha_nac": "2000-09-06",
	"genero": "9091",
	"direccion": "los andes",
	"correo": "9091@gmail.com",
	"telefono": "9091",
	"nombre_usuario": "9091",
	"contrasenia": "9091@9091",
	"rol": "administrador"
}

### EDITAR ADMINISTRADOR
PUT http://127.0.0.1:3000/api/administrador/4
Content-Type: application/json
Accept: application/json

{
	"ci": "4444",
	"nombre": "zzz",
	"fecha_nac": "1999-09-06",
	"genero": "Masculino",
	"direccion": "Los andes",
	"correo": "zzz@gmail.com",
	"telefono": "4444",
	"nombre_usuario": "zzz",
	"contrasenia": "zzz@4444",
	"rol": "colaborador"
}
