### LISTAR USUARIO
GET http://127.0.0.1:3000/api/usuario

### LOGIN USUARIO
POST http://127.0.0.1:3000/api/auth/login/
Content-Type: application/json
Accept: application/json

{
    "correo": "rodrigo@gmail.com",
    "contrasenia": "rodrigo@1111"
}

### AGREGAR CONTACTO
POST http://127.0.0.1:3000/api/contacto
Content-Type: application/json
Accept: application/json

{
	"nombre_contacto": "c",
	"telefono": "c",
	"id_usuario": "12"
}

### EDITAR CONTACTO DE USUARIO
PUT http://127.0.0.1:3000/api/contacto/13/usuario/4
Content-Type: application/json
Accept: application/json

{
	"nombre_contacto": "carmen",
	"telefono": "76545",
	"id_usuario": "4"
}


### LISTAR CONTACTO DE USUARIO
GET http://127.0.0.1:3000/api/contacto/usuario/4

### ELIMINAR CONTACTOS
DELETE http://127.0.0.1:3000/api/contacto/15/usuario/4
